grafana:
  adminPassword: admin123

prometheus:
  prometheusSpec:
    replicas: 1 
    serviceMonitorSelectorNilUsesHelmValues: false 
    serviceMonitorNamespaceSelector: {}  
    serviceMonitorSelector: {}  
    additionalScrapeConfigs: [] 

nodeExporter:
  enabled: true