apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-habit-tracker
  labels:
    app: habit-tracker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: habit-tracker
  template:
    metadata:
      labels:
        app: habit-tracker
    spec:
      containers:
      - name: habit-tracker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000