apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-habit-tracker-service
spec:
  selector:
    app: habit-tracker
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }} 