apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-service
  labels: 
    app: habit-tracker
spec:
  selector:
    app: habit-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: NodePort